name: Actions

on: push

jobs:
  build-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Current Directory
        run: ls -al