name: Actions

on: push

jobs:
  build-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.x'
      - name: Install Dependencies
        working-directory: react-actions
        run: npm ci