name: Job02

on:
  push:
  pull_request:
    schedule:
      - cron: '*/5 * * * *' # every 5 minutes
    workflow_dispatch:

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Show Trigger
        run: echo "Triggered by ${{ github.event_name }} event"