name: Runners

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Show Linux OS
        run: |
          echo "Runner OS: $RUNNER_OS"

  windows:
    runs-on: windows-latest
    steps:
      - name: Show Windows OS
        shell: bash
        run: |
          echo "Runner OS: $RUNNER_OS"


  macos:
    runs-on: macos-latest
    steps:
      - name: Show MacOS OS
        run: |
          echo "Runner OS: $RUNNER_OS"