name: Workflows

on:
  push:
  pull_request:
    workflow_dispatch:

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Show Trigger
        run: echo "Triggered by ${{ github.event_name }} event"
